language: cpp
sudo: false
dist: trusty

matrix:
  include:
  - os: linux
    env:
    - _CC: gcc-4.9
    - _CXX: g++-4.9
    - CMAKE_URL=https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz
    - CMAKE_DIRNAME=cmake-3.4.0-Linux-x86_64
    - AUTOWIRING_URL=https://github.com/leapmotion/autowiring/releases/download/v1.0.3/autowiring-1.0.3-Linux-amd64.tar.gz
    - AUTOWIRING_DIRNAME=autowiring-1.0.3-Linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - boost-latest
        packages:
          - gcc-4.9
          - g++-4.9
          - libcurl3
  - os: osx
    env:
    - _CC: clang
    - _CXX: clang++
    - CMAKE_URL=https://cmake.org/files/v3.4/cmake-3.4.0-Darwin-x86_64.tar.gz
    - CMAKE_DIRNAME=cmake-3.4.0-Darwin-x86_64/CMake.app/Contents
    - AUTOWIRING_URL=https://github.com/leapmotion/autowiring/releases/download/v1.0.3/autowiring-1.0.3-Darwin.tar.gz
    - AUTOWIRING_DIRNAME=autowiring-1.0.3-Darwin

before_install:
  # Enforce whitespace guidelines
  - ./scripts/whitespace_check.sh

  # Enforce Leap Motion copyright notice
  - ./scripts/copyright_check.sh

install:
  # CMake 3.4
  - mkdir etc
  - pushd etc
  - curl -L $CMAKE_URL | tar xz &
  - curl -L $AUTOWIRING_URL | tar xz &
  - wait
  - popd

before_script:
  - curl --version
  - export CC=$_CC
  - export CXX=$_CXX
  - $CXX --version
  - export CPATH=/usr/include/c++/4.8:/usr/include/x86_64-linux-gnu/c++/4.8/:$CPATH
  - export LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8:$LD_LIBRARY_PATH

script:
  # Build LeapHTTP, run unit tests, and install
  - >
    etc/$CMAKE_DIRNAME/bin/cmake .
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_PREFIX_PATH:PATH=etc/
  - make -j 4 LeapHTTPTest || make LeapHTTPTest
  - ctest --output-on-failure --timeout 30

after_failure:
  - cat Testing/Temporary/LastTest.log 2> /dev/null